#!/bin/sh
# Check clang formatting
git diff --cached --name-only --diff-filter=ACMRT | grep -E "\.([ch]|cpp)$" | xargs -n1 clang-format -style=llvm -output-replacements-xml | grep "<replacement " >/dev/null
if [ $? -ne 1 ]
then 
    echo "Commit did not match clang-format"
    echo "Run 'git clang-format' to automatically format staged files"
    exit 1;
fi
