#pragma once
#include <aerial_autonomy/controller_hardware_connectors/builtin_velocity_controller_drone_connector.h>
#include <aerial_autonomy/controller_hardware_connectors/joystick_velocity_controller_drone_connector.h>
#include <aerial_autonomy/controller_hardware_connectors/manual_rpyt_controller_drone_connector.h>
#include <aerial_autonomy/controller_hardware_connectors/position_controller_drone_connector.h>