#!/usr/bin/env python

import os
import sys
import argparse
import re

"""
Extract line coverage and function coverage from
lcov 
"""

ACCEPTABLE_COVERAGE=99

def main():
  # Arguments
  parser = argparse.ArgumentParser()
  parser.add_argument ("info",         action="store",      help="Path to Test coverage info generated by lcov")
  parser.add_argument ("--threshold", action="store",      help="Min acceptable line coverage percentage (Default: %s)"%(ACCEPTABLE_COVERAGE), default=ACCEPTABLE_COVERAGE, type=int)
  ns = parser.parse_args()
  if not ns:
    print ("ERROR: Couldn't parse parameters")
    sys.exit(-1)

  if not os.path.exists(ns.info):
    print "Cannot find test coverage info. Generate it using 'scripts/generate_test_coverage.bash'"
    sys.exit(-1)

  os.system('lcov --summary {0} 2> /tmp/test_coverage_summary'.format(ns.info,))

  coverage_file = open('/tmp/test_coverage_summary', 'r')

  number_list = []

  for line in coverage_file:
    for s in line.split():
      if s[-1] == '%':
        number_list.append(int(round(float(s[:-1]))))

  # Check function coverage, line coverage and throw errors if necessary
  if number_list[0] < ns.threshold:
    sys.exit(ns.threshold - number_list[0])
  return;

if __name__ == "__main__":
  main()
