uav_system_handler_config{
  uav_parser_type: "quad_simulator_parser/QuadSimParser"
  uav_controller_timer_duration: 20

  base_config {
    state_machine_timer_duration: 20
    status_timer_duration: 50
  }

  uav_system_config {
    minimum_battery_percent: 40
    minimum_takeoff_height: 0.5
    landing_height: 0.1
  }
}

rpyt_velocity_controller_config{
  kp: 1.0
  ki: 0.0
  kt: 0.15
}

velocity_sensor_config{
  sensor_transform: 0.0
  sensor_transform: 0.0
  sensor_transform: 0.0
  sensor_transform: -1.57
  sensor_transform: 0.0
  sensor_transform: 0.0

  sensor_frequency: 30.0
}

manual_velocity_controller_config{
  max_channel1: 10000
  max_channel2: 10000
  max_channel3: 10000
  max_channel4: 10000

  max_velocity: 1
  controller_frequency: 30
}

use_dynamic_reconfigure: true
