uav_parser_type: "dji_parser/DjiParser"
uav_controller_timer_duration: 20

base_config {
  state_machine_timer_duration: 20
  status_timer_duration: 50
}

uav_system_config {
  minimum_battery_percent: 40
  minimum_takeoff_height: 0.5
  landing_height: 0.1
  goal_position_tolerance {
    x: 0.05
    y: 0.05
    z: 0.05
  }
}
