uav_controller_timer_duration: 20

base_config {
  state_machine_timer_duration: 20
  status_timer_duration: 50
}

uav_system_config {
  uav_parser_type: "dji_parser/DjiParser"
  minimum_battery_percent: 40
  minimum_takeoff_height: 0.5
  landing_height: 0.1
  position_controller_config {
    goal_position_tolerance {
      x: 0.05
      y: 0.05
      z: 0.05
    }
  }
  velocity_controller_config {
    goal_velocity_tolerance {
      vx: 0.1
      vy: 0.1
      vz: 0.1
    }
  }
}
