uav_controller_timer_duration: 20

uav_arm_system_handler_config {
  arm_controller_timer_duration: 20
}

base_config {
  state_machine_timer_duration: 20
  status_timer_duration: 50
}

uav_system_config {
  uav_parser_type: "dji_parser/DjiParser"
  minimum_battery_percent: 25
  minimum_takeoff_height: 0.8
  landing_height: 0.1
  position_controller_config {
    goal_position_tolerance {
      x: 0.05
      y: 0.05
      z: 0.05
    }
  }

  velocity_controller_config {
    goal_velocity_tolerance {
      vx: 0.1
      vy: 0.1
      vz: 0.1
    }
  }
  rpyt_based_position_controller_config {
    velocity_based_position_controller_config {
      position_gain: 0.7
      yaw_gain: 0.3
      max_velocity: 1.0
      position_i_gain: 0.0
      yaw_i_gain: 0.0
      position_saturation_value: 0.0
      yaw_saturation_value: 0.0

      position_controller_config {
        goal_position_tolerance {
          x: 0.1
          y: 0.1
          z: 0.1
        }
      }
    }

    rpyt_based_velocity_controller_config{
      kp_xy: 2.0
      ki_xy: 0.0
      kp_z: 2.0
      ki_z: 0.2
      kt: 0.21

      min_thrust: 10
      max_thrust: 100
      max_rp: 1.57

      velocity_controller_config{
        goal_velocity_tolerance{
          vx: 0.1
          vy: 0.1
          vz: 0.1
        }
      }
    }
  }

  thrust_gain_estimator_config {
    kt: 0.18
    buffer_size: 10
  }

  uav_vision_system_config {
    tracker_type: "Alvar"

    camera_transform {
      position {
        x: 0.2093
        y: 0.0063
        z: -0.0836
      }
      rotation {
        r: 1.9372
        p: 0
        y: 1.5794
      }
    }

    tracking_offset_transform {
      position {
        x: 0
        y: 0
        z: 0
      }
      rotation {
        r: -1.5708
        p: 0
        y: 0
      }
    }

    desired_visual_servoing_distance: 0.48

    constant_heading_depth_controller_config {
      radial_gain: 0.6
      tangential_gain: 1.3
      yaw_gain: 0.3
      max_velocity: 0.2
      min_velocity: 0.0
      max_yaw_rate: 0.3
      position_controller_config {
        goal_position_tolerance {
          x: 0.05
          y: 0.05
          z: 0.05
        }
        goal_yaw_tolerance: 0.08
      }
    }

    velocity_based_relative_pose_controller_config {
      velocity_based_position_controller_config {
        position_gain: 0.7
        yaw_gain: 0.5
        max_velocity: 0.25
        max_yaw_rate: 0.3
        yaw_i_gain: 0.0
        position_i_gain: 0.055
        position_saturation_value: 0.03
        yaw_saturation_value: 0.0
        position_controller_config {
          goal_position_tolerance {
            x: 0.04
            y: 0.04
            z: 0.04
          }
          goal_yaw_tolerance: 0.1
        }
      }
    }

    uav_arm_system_config {
      arm_transform {
        position {
          x: 0.17
          y: 0
          z: -0.109
        }
        rotation {
          r: 0
          p: -1.5707
          y: 3.141
        }
      }

      position_controller_config {
        goal_position_tolerance {
          x: 0.02
          y: 0.02
          z: 0.02
        }
        goal_rotation_tolerance: 6
      }
      arm_system_config {
        pose_controller_config {
          goal_position_tolerance {
            x: 0.02
            y: 0.02
            z: 0.02
          }
          goal_rotation_tolerance: 6
        }
        arm_parser_type: "SimpleArm"
      }
    }
  }
}

