ddp_config {
  # State cost
  # XYZ
  Q: 0
  Q: 0
  Q: 0
  # RPY
  Q: 0
  Q: 0
  Q: 0
  # Vxyz
  Q: 4
  Q: 4
  Q: 4
  # RPYdot
  Q: 0
  Q: 0
  Q: 0
  # RPY_cmd
  Q: 0
  Q: 0
  Q: 0
  # Joint_angles
  Q: 0
  Q: 0
  # Joint_velocities
  Q: 0
  Q: 0
  # Joint_cmd
  Q: 0
  Q: 0
  # Terminal gains
  # XYZ
  Qf: 200
  Qf: 200
  Qf: 200
  # RPY
  Qf: 100
  Qf: 100
  Qf: 100
  # Vxyz
  Qf: 100
  Qf: 100
  Qf: 100
  # RPYdot
  Qf: 100 
  Qf: 100
  Qf: 100
  # RPY_cmd
  Qf: 0.1
  Qf: 0.1
  Qf: 0.1
  # Joint_angles
  Qf: 50
  Qf: 50
  # Joint_velocities
  Qf: 5
  Qf: 5
  # Joint_cmd
  Qf: 0.1
  Qf: 0.1
  # Control cost
  # Thrust
  R: 6.0
  # Rpyd dot
  R: 4.0
  R: 4.0
  R: 4.0
  # desired joint velocities
  R: 0.1
  R: 0.1
  # Trajectory length
  N: 100
  # Max iterations
  max_iters: 2
  # Min cost decrease
  min_cost_decrease: 1e-4
  # Look ahead time
  look_ahead_time: 0.02
  # Max cost
  max_cost: 100.0
}

weights_folder: "neural_network_model_data/tensorflow_model_vars_16_8_tanh/"
goal_position_tolerance: 0.25
goal_velocity_tolerance: 0.25
goal_joint_angle_tolerance: 0.15
goal_joint_velocity_tolerance: 0.15
# Lower bound
lower_bound_control: 0.6
lower_bound_control: -0.6
lower_bound_control: -0.6
lower_bound_control: -0.6
lower_bound_control: -0.7
lower_bound_control: -0.7
# Upper bound
upper_bound_control: 1.4
upper_bound_control: 0.6
upper_bound_control: 0.6
upper_bound_control: 0.6
upper_bound_control: 0.7
upper_bound_control: 0.7
