visual_servoing_state_machine_config {

  # Alvar testing
  #relative_pose_goals {
  #  position {
  #    x: 0.0
  #    y: -0.7
  #    z: 0.0
  #  }
  #  yaw: 1.5708
  #}
  #relative_pose_goals {
  #  position {
  #    x: 0.0
  #    y: -0.45
  #    z: 0.0
  #  }
  #  yaw: 1.5708
  #}
  #relative_pose_goals {
  #  position {
  #    x: 0.0
  #    y: -0.67
  #    z: 0.0
  #  }
  #  yaw: 1.5708
  #}

  # PrePlace
  relative_pose_goals {
    position {
      x: 0.7
      y: 0
      z: -0.07
    }
    yaw: 3.14
  }

  # Place
  relative_pose_goals {
    position {
      x: 0.55
      y: 0
      z: -0.07
    }
    yaw: 3.14
  }

  # Checking
  relative_pose_goals {
    position {
      x: 0.67
      y: 0
      z: -0.07
    }
    yaw: 3.14
  }

  orange_tracking_state_machine_config {
    pick_timeout: 10000
    window {
      position {
        x: 0.20
        y: 0.20
        z: 0.20
      }
      yaw: 0.15
    }
    
  }
  connector_type: RPYTPose
}
poly_reference_config {
  max_velocity: 0.15
  min_tf: 4
  forward_noise_amplitude: 0.5
  forward_noise_frequency: 0.25
  z_noise_amplitude: 0.03
  z_noise_frequency: 0.125
  add_noise: false
}
