uav_parser_type: "quad_simulator_parser/QuadSimParser"
uav_controller_timer_duration: 20

uav_arm_system_handler_config {
  arm_controller_timer_duration: 20
  arm_parser_type: "ArmSimulator"
}


base_config {
  state_machine_timer_duration: 20
  status_timer_duration: 50
}

uav_system_config {
  minimum_battery_percent: 40
  minimum_takeoff_height: 0.5
  landing_height: 0.1

  position_controller_config {
    goal_position_tolerance {
      x: 0.05
      y: 0.05
      z: 0.05
    }
  }

  velocity_based_position_controller_config {
    position_gain: 0.9
    yaw_gain: 0.3
    max_velocity: 0.25
    max_yaw_rate: 0.3
    position_i_gain: 0.0
    yaw_i_gain: 0.0
    position_controller_config {
      goal_position_tolerance {
        x: 0.04
        y: 0.04
        z: 0.04
      }
      goal_yaw_tolerance: 0.1
    }
  }

  velocity_controller_config {
    goal_velocity_tolerance {
      vx: 0.1
      vy: 0.1
      vz: 0.1
    }
  }

  uav_vision_system_config {
    tracker_type: "ROI"
    camera_transform: 0
    camera_transform: 0
    camera_transform: 0
    camera_transform: -1.5708
    camera_transform: 0
    camera_transform: -1.5708

    tracking_offset_transform: 0.0
    tracking_offset_transform: 0.0
    tracking_offset_transform: 0.0
    tracking_offset_transform: -1.5708
    tracking_offset_transform: 0.0
    tracking_offset_transform: 0.0

    desired_visual_servoing_distance: 1.0
    constant_heading_depth_controller_config {
      radial_gain: 0.1
      tangential_gain: 0.1
      yaw_gain: 0.1
      max_velocity: 1
      max_yaw_rate: 0.1
      position_controller_config {
        goal_position_tolerance {
          x: 0.05
          y: 0.05
          z: 0.05
        }
        goal_yaw_tolerance: 0.04
      }
    }
    relative_pose_goals {
      position {
        x: 0
        y: -.40
        z: .19
      }
      yaw: 0
    }

    velocity_based_relative_pose_controller_config {
      velocity_based_position_controller_config {
        position_gain: 0.9
        yaw_gain: 0.3
        max_velocity: 0.25
        max_yaw_rate: 0.3  
        position_i_gain: 0.0
        yaw_i_gain: 0.0
        position_controller_config {
          goal_position_tolerance {
            x: 0.04
            y: 0.04
            z: 0.04
          }
          goal_yaw_tolerance: 0.1
        }
      }
    }
    uav_arm_system_config {
      arm_goal_transform: -0.2
      arm_goal_transform: 0.0
      arm_goal_transform: -0.15
      arm_goal_transform: 0.0
      arm_goal_transform: 0.0
      arm_goal_transform: 0.0

      arm_transform: 0.15
      arm_transform: 0.0
      arm_transform: -0.25
      arm_transform: 3.14159
      arm_transform: 0.0
      arm_transform: 0.0

      position_controller_config {
        goal_position_tolerance {
          x: 0.05
          y: 0.05
          z: 0.05
        }
        goal_rotation_tolerance: 0.05
      }
    }
  }
}
