kp_xy: 5
kp_z: 10
kd_xy: 5
kd_z: 10
k1: 0.3
k2: 0.3
jxx: 0.05
jyy: 0.05
jzz: 0.08
mass: 3.4
goal_position_tolerance {
  x: 0.02
  y: 0.02
  z: 0.02
}
goal_velocity_tolerance {
  vx: 0.02
  vy: 0.02
  vz: 0.02
}
