mpc_visualization_timer_duration: 50

base_config {
  state_machine_timer_duration: 20
  status_timer_duration: 50
}

uav_system_config {
  uav_controller_timer_duration: 20
  uav_parser_type: "quad_simulator_parser/QuadSimParser"
  minimum_battery_percent: 40
  minimum_takeoff_height: 0.5
  landing_height: 0.1

  position_controller_config {
    goal_position_tolerance {
      x: 0.05
      y: 0.05
      z: 0.05
    }
  }

  velocity_controller_config {
    goal_velocity_tolerance {
      vx: 0.1
      vy: 0.1
      vz: 0.1
    }
  }
  mpc_connector_config {
    velocity_exp_gain: 0.0
    rpydot_gain: 0.0
    use_perfect_time_diff: false
  }
  quad_mpc_controller_config {
    default_thrust_gain: 0.16
    ddp_config {
      # State cost
      # XYZ
      Q: 1
      Q: 1
      Q: 1
      # RPY
      Q: 0
      Q: 0
      Q: 0
      # Vxyz
      Q: 4 
      Q: 4 
      Q: 4 
      # RPYdot
      Q: 0
      Q: 0
      Q: 0
      # RPY_cmd
      Q: 0
      Q: 0
      Q: 0
      # Terminal gains
      # XYZ
      Qf: 10
      Qf: 10
      Qf: 10
      # RPY
      Qf: 10
      Qf: 10
      Qf: 10
      # Vxyz
      Qf: 10
      Qf: 10
      Qf: 10
      # RPYdot
      Qf: 10
      Qf: 10
      Qf: 10
      # RPY_cmd
      Qf: 0.1
      Qf: 0.1
      Qf: 0.1
      # Control cost
      # Thrust
      R: 6.0
      # Rpyd dot
      R: 4.0
      R: 4.0
      R: 4.0
      # Trajectory length
      N: 100
      # Max iterations
      max_iters: 2
      # Min cost decrease
      min_cost_decrease: 1e-4
      # Look ahead time
      look_ahead_time: 0.2
      # Max cost
      max_cost: 500.0
    }

    goal_position_tolerance: 0.15
    goal_velocity_tolerance: 0.15
    # Lower bound
    lower_bound_control: 0.8
    lower_bound_control: -0.6
    lower_bound_control: -0.6
    lower_bound_control: -0.6
    # Upper bound
    upper_bound_control: 1.2
    upper_bound_control: 0.6
    upper_bound_control: 0.6
    upper_bound_control: 0.6
  }
  rpyt_based_position_controller_config {
    velocity_based_position_controller_config {
      position_gain: 0.7
      yaw_gain: 0.3
      max_velocity: 1.0
      position_i_gain: 0.0
      yaw_i_gain: 0.0
      position_saturation_value: 0.0
      yaw_saturation_value: 0.0
      max_yaw_rate: 3.14

      position_controller_config {
        goal_position_tolerance {
          x: 0.1
          y: 0.1
          z: 0.1
        }
      }
    }

    rpyt_based_velocity_controller_config{
      kp_xy: 2.0
      ki_xy: 0.1
      kp_z: 2.0
      ki_z: 0.0
      kt: 0.21

      min_thrust: 10
      max_thrust: 100
      max_rp: 1.57

      velocity_controller_config{
        goal_velocity_tolerance{
          vx: 0.1
          vy: 0.1
          vz: 0.1
        }
      }
    }
  }
  thrust_gain_estimator_config {
    kt: 0.17
    buffer_size: 10
  }
  visualize_mpc_trajectories: true
  visualizer_config {
    parent_frame: "/world"
    skip_segments: 10
    trajectory_color {
      r: 0
      g: 1
      b: 0
    }
    desired_trajectory_color {
      r: 1
      g: 0
      b: 0
      a: 0.4
    }
  }
  uav_vision_system_config {
    tracker_type: "Simulated"

    camera_transform {
      position {
        x: 0
        y: 0
        z: 0
      }
      rotation {
        r: -1.5708
        p: 0
        y: -1.5708
      }
    }

    tracking_offset_transform {
      position {
        x: 0
        y: 0
        z: 0
      }
      rotation {
        r: 0
        p: 0
        y: 0
      }
    }

    desired_visual_servoing_distance: 1.0
    constant_heading_depth_controller_config {
      radial_gain: 0.1
      tangential_gain: 0.1
      yaw_gain: 0.1
      max_velocity: 1
      max_yaw_rate: 0.1
      position_controller_config {
        goal_position_tolerance {
          x: 0.05
          y: 0.05
          z: 0.05
        }
        goal_yaw_tolerance: 0.04
      }
    }
    rpyt_based_relative_pose_controller_config {
      velocity_based_relative_pose_controller_config {
        velocity_based_position_controller_config {
          position_gain: 0.3
          yaw_gain: 0.3
          max_velocity: 0.2
          max_yaw_rate: 0.3
          position_controller_config {
            goal_position_tolerance {
              x: 0.1
              y: 0.1
              z: 0.1
            }
            goal_yaw_tolerance: 0.1
          }
        }
      }
      rpyt_based_velocity_controller_config {
        kp_xy: 1.0
        ki_xy: 0.0
        kt: 0.2
      }
    }
    particle_reference_config {
      kp_x : 0.2
      kp_y : 0.2
      kp_z : 0.2
      kp_yaw : 0.2
      max_velocity : 0.2
      max_yaw_rate : 0.2
    }
  }
}
